// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjyapciwajfrsgldrizi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqeWFwY2l3YWpmcnNnbGRyaXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzc2MjYsImV4cCI6MjA2ODk1MzYyNn0.LkkXucvuULN6U8ZrboWsTH1Yi4QGU6nFKwJAr7-TKoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});